<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/12/02 04:08:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql',
  'username' => 'hradmin',
  'password' => 'hradmin2016',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
